[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pubquiztrainer"
version = "0.1.0"
description = "Pub Quiz Training."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.3",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "tzdata>=2026.3",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
pubquiz-scheduler = "pubquiztrainer.scheduler:main"
pubquiz-question = "pubquiztrainer.question:main"
pubquiz-answer = "pubquiztrainer.answer:main"
